### ISSUE TITLE
Missing lecture overlap

### ISSUE THREAD

**Issue by michael-k** [sfanous/cantrill.io-courses-scraper#2]
It looks like the following lectures exist both in the SAA and the SA Pro course (I haven't checked the other courses, but they are probably affected as well):

- NACLs
  - SAA: `[ASSOCIATESHARED] Network Access Control Lists (NACLs)`, duration: 12:38
  - SA Pro: `Network Access Control Lists (NACL)`, duration: 12:38
- Security Groups
  - SAA: `[ASSOCIATESHARED] Security Groups (SG)`, duration: 11:48
  - SA Pro: `Security Groups`, duration: 11:48

----

Great work! :heart:

**Comment by sherif-fanous** [comment]
Looks like Adrian made some changes to the tags. I'll look into it this weekend if I get some time.

Thanks for reporting the issues.

**Comment by sherif-fanous** [comment]
Fixed in latest commit. Please check and report any other issues please.
