### ISSUE TITLE
Highlight unique lectures for user-provided course combinations

### ISSUE THREAD

**Issue by michael-k** [sfanous/cantrill.io-courses-scraper#3]
I did go through Adrian's _Solutions Architect Associate_ and _Professional_ courses and now I'm on to the _Advanced Networking Specialty_.  The charts tab tells me that I only need to watch ~ 24 %/8 hours of the videos which is nice.

I can use the courses tab to figure out which ones are duplicate.  But since all three associate courses (#2c77ea) and the two professional courses (#3dcac0) share the same color respectively.  Since I've only gone through one course each, it's a bit of work to figure out which lectures are duplicates for lectures that aren't shared with all 3 associate and all 2 professional courses.

It would be nice if one could select the courses one has already gone though and then the unique lectures get highlighted.

---

I've already gone through the specialty course and marked all shared lectures as complete, therefore I'm not in an urgent need.  But since I have 2 associate and 1 professional courses to go through afterwards, I'd much appreciate such a feature.

**Comment by sherif-fanous** [comment]
Hey @michael-k

Did you try the Study Guide functionality? I believe it does exactly what you're looking for if I'm understanding you correctly.

**Comment by michael-k** [comment]
Totally missed that :+1:, but to be fair it's quite new. ;)

Thanks for your great work! :heart:
