### ISSUE TITLE
Question: Exposing courses.json?

### ISSUE THREAD

**Issue by ghassanachi** [sfanous/cantrill.io-courses-scraper#8]
First of all, thank you so much for building this! 

I saw the website being referred by @acantril on Slack and was thrilled to discover its existence. 

I am considering building a small browser extension to tag lectures within https://learn.cantrill.io/ with all the courses they appear in. This would make it easier to filter out duplicates that may already be covered in other courses. The general flow I have in mind is:

1. The browser extension would have buttons that can be toggled for each of the courses that the user has completed.
2. When the user starts a new course, any duplicate lectures would be marked with a small badge indicating the course in which they were covered. If a lecture was covered in more than one course, all courses would be displayed.

Here is a small screenshot showing a simple version of what the badges might look like. I may further reduce their size and position them absolutely to avoid interfering with the existing layout. 

![Screenshot demoing badges](https://user-images.githubusercontent.com/11818566/219509593-2f7a6188-0d6b-467e-b3cb-10a6cda6adfb.png)

Since your website already generates all of the information that would be needed to build this extension, I hope to not duplicate the work/logic, especially since the matching relies on fuzzy matching, which could lead to different results between what I would build and what can be found here. 

Thus, I was wondering if you would consider exposing the generated courses JSON file to the public internet. I noticed that it can be found at the top of [index.js](https://cantrill.io.i-aws.cloud/index.js) with `const courses = _.chain(JSON.parse('<courses>'))`, but downloading and parsing that file to strip the JSON would be very hacky and error-prone. Ideally, I would prefer a way of fetching the JSON directly from an endpoint. 

Please let me know your thoughts on exposing this file. If you think it's a good idea, I'm happy to work on a pull request for this. 

Feel free to close this whenever, I wasn't sure what the best channel was to ask a question.

**Comment by sherif-fanous** [comment]
Hey @ghassanachi 

I've hacked something very quickly into the dev app.

Let me know if such an endpoint would work for you

http://cantrill.io-dev.i-aws.cloud/courses.json

If it would then I'll work on getting this added into the prod app over the weekend.

**Comment by ghassanachi** [comment]
Looks great! Thanks!

I'll work on the extension tomorrow, and update this issue once I have a working prototype.

If you like the idea of the extension and you are interested in consolidating the codebases, I'd be happy to add the extension code directly to this repo and add the necessary CI/CD pipelines to release the extension.

**Comment by ghassanachi** [comment]
Hey @sfanous, 

Just wanted to give you a quick update. I got the initial version of the application working on Chrome and Firefox and here is the link to the repo https://github.com/ghassanachi/cantrill-web-ext.

Firefox was a little more restrictive when it came of CORS policies and HTTP usage, so I ended up adding a small https/cors reverse_proxy for `http://cantrill.io-dev.i-aws.cloud/courses.json` (proxy is hosted at https://cantrill-json.ghassanachi.com -- uri is optional since the proxy is rewriting the request).

If you want to test the extension, you can use the following steps:
### Firefox: 
* Clone the repo and install dependencies witn `yarn install` or `npm install`
* Build the extension with `yarn package:firefox` or `npm run package:firefox`. This will generate a `web-ext-artifacts` folder containing the zip file for the extension
* Head to the URL `about:debugging` in Firefox
* Click on `This Firefox` on the sidebar
* Click on `Load Temporary Add-On`, an select the extension `zip` from the `web-ext-artifacts` folder

### Chrome
* Clone the repo and install dependencies witn `yarn install` or `npm install`
* Build the extension with `yarn build` or `npm run build`
* Head to the URL `chrome://extensions` in Chrome
* Toggle the `Developer mode` switch at the top right of the page 
* Click on the `Load unpacked` and select the `dist` folder in the cloned repository.

Since I don't own the courses, I'm still missing information about for the `Advanced Networking` and `Security` Specialties (specifically the `<course_id>` url parameter for each of the courses). But once I have those I'll work on releasing the extension to the Firefox and Chrome Stores. 

If possible I'd like to point to an `https/production` version of the `http://cantrill.io-dev.i-aws.cloud/courses.json` file directly on your domain.

**Comment by sherif-fanous** [comment]
Hey @ghassanachi 

I've copied the file to the production bucket -> https://cantrill.io.i-aws.cloud/courses.json but have not updated the code there yet so this file will not get updated automatically. I plan to release this soon.

Also check out https://cantrill.io.i-aws.cloud/config_files/courses.json for the list of courses my app currently tracks.

I'll try to give the extension a test drive over the weekend.

**Comment by ghassanachi** [comment]
Thanks @sfanous! No worries and no rush on getting the file to automatically update. I don't think the courses change that often, and being able to point it at the production endpoint should be more then sufficient for now. 

Thanks for pointing out  https://cantrill.io.i-aws.cloud/config_files/courses.json, I had that information hardcoded on my end (I might still need that just because I am mapping the courses to local images), but this should allow me to stay consistent with the courses being tracked on your end. 

Thanks again for all the help.

**Comment by acantril** [comment]
> I don't think the courses change that often

Bad assumption to make, i change courses v. often.

**Comment by ghassanachi** [comment]
Thanks for the info @acantril. 

If that is the case, I'll be a little more patient with the initial release and make sure to refresh course data on the extension more often, and I'll wait for the automatic update of the `couses.json` file to be published. 

@sfanous, if you are a little busy and  want a hand for the automatic update of `courses.json`, let me know and I would be happy to help when I have a little bit of time.

**Comment by sherif-fanous** [comment]
@ghassanachi All is done now. There was some down time yesterday as I had been wanting to migrate this app to a separate AWS account within my Org but all should be good now and the `courses.json` file is now updated on every scheduled run.
